### ISSUE TITLE
Path normalization would prevent VSCode opening the same source in different tabs

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#101]
Our user [complains](https://github.com/matepek/vscode-catch2-test-adapter/issues/141), quoting:
> In the test explorer click on a test that resides in a file with a name such as TestClass.cpp. Then the editor opened with name testcase.cpp. This cause some problems for example if the file was opened, there we have two tabs for one file, and intellisense will be disabled in second file, and...

I could do some normalization in case of my extension (on Windows os), but doing it in this repo would benefit all the adapters.

(Slightly related to #35. )

**Comment by hbenl** [comment]
Unfortunately normalizing won't work here (unless it was VS Code itself that would normalize all filenames). The issue is that the casing information of the filename has been lost and VS Code expects case-exact filenames. Reconstructing the casing information is [difficult](https://stackoverflow.com/questions/33086985/how-to-obtain-case-exact-path-of-a-file-in-node-js-on-windows?noredirect=1) and slow, so I'd rather expect test adapters to ensure that the casing information isn't lost.

**Comment by matepek** [comment]
In case of c++ this information is coming from the test framework which uses compiler macros. I think I can restore, just wondering are other adapters would benefit of this functionality.

**Comment by hbenl** [comment]
I haven't heard about any other adapters having this problem. Even if they were, this is a problem specific to the testing framework, so I think it should be handled by the adapter and the solution could be shared via a library (e.g. the vscode-test-adapter-util npm package).
