### ISSUE TITLE
Perhaps ellipsize test case names with tooltip

### ISSUE THREAD

**Issue by Gert-dev** [hbenl/vscode-test-explorer#102]
First off, thanks for this nice extension.

The PHP plugin shows the entire FQCN of the test case class, which makes items in the tree very long. This in turn makes it hard to reach the button to navigate to the source - which I didn't even know existed and I wanted to report an issue about it, until I discovered #69.

An example to demonstrate how long the test names are:

![Example](https://user-images.githubusercontent.com/24809863/69906683-247bdd00-13bf-11ea-8343-a78cf99d8564.png)

Would it be possible to ellipsize long test names (and e.g. show the full name in a tooltip on hover), or ellipsize the first part of the name (as the last part is usually the most important)? The idea is that there would be no horizontal scrollbar and the action buttons would always be visible on hover to the right. This would be similar to what the Tree Style Tabs extension does in Firefox:

![Firefox Tree Style Tabs](https://user-images.githubusercontent.com/24809863/69906707-76246780-13bf-11ea-8355-c75a839602e8.png)

Thanks!

**Comment by hbenl** [comment]
Long test names are already being ellipsized, there is no horizontal scrollbar, the action buttons are visible and the full test name appears on hover:
![Screenshot_2019-12-08_12-12-53](https://user-images.githubusercontent.com/16060807/70388586-3a3b6480-19b4-11ea-9816-feeb6c3c045a.png)
All of this is actually standard VS Code behavior for contributed tree views.
The only thing that is missing here is the ability to ellipsize the _first part_ of the name. This could only be done statically (i.e. the first part would _always_ be cut off, even if you increase the width of the side bar) because VS Code doesn't offer any APIs for influencing how it ellipsizes the texts in a tree view. If this is desired, it should be done by the test adapter, it can specify the full name for the tooltip [here](https://github.com/hbenl/vscode-test-adapter-api/blob/aaccca7987e11afa4f37ceb2eb2193e33bed61b4/src/index.ts#L216).

**Comment by Gert-dev** [comment]
Thanks for the response. I've created an issue in the adapter repository here: https://github.com/recca0120/vscode-phpunit/issues/47.
