### ISSUE TITLE
Using super() on a class of node_modules throws an error

### ISSUE THREAD

**Issue by peni4142** [hbenl/vscode-test-explorer#107]
Hi,
I have a little TypeScript example. I do not know if I am right here, but this only fails in the vscode-test-explorer. I can transpile that and run without any problems, except in that test.

I think I gave you everything to reproduce it by yourself easily. And I hope it is self-explaining. "settings.json" is missing in the zip.

[bugs.zip](https://github.com/hbenl/vscode-test-explorer/files/3957122/bugs.zip)

my settings
```
{
    "mochaExplorer.files": [xxx ],
    "mochaExplorer.require": "ts-node/register",
    "mochaExplorer.ui":"tdd",
    "mochaExplorer.pruneFiles":true
}
```

```
import { SuperModule } from "test/index";

class Test extends SuperModule {
    constructor() {
        super();
    }
}

suite("bug", (): void => {
    test("without super", (): void => {
        // tslint:disable-next-line: no-unused-expression
        new SuperModule();

        // works
    });
    test("super", (): void => {
        // tslint:disable-next-line: no-unused-expression
        new Test();
        // does not work
    });
});
```

in the module:
```
node_modules
   |-test
        -index.js
```
```
class SuperModule{
    //
}

exports.SuperModule = SuperModule
```

Error:
```
TypeError: Class constructor SuperModule cannot be invoked without 'new'
    at new Test (development\bugs\src\bug.test.ts:21:9)
    at Context.<anonymous> (development\bugs\src\bug.test.ts:32:9)
```

typescript version: 3.7.3 (installed by `npm i typescript -g`)

Maybe you have a hint to configure the mochaExplorer in huge projects. Actual this extension slows my whole vs code.

**Comment by hbenl** [comment]
Thanks for the detailed reproduction steps!
I can reproduce the issue but it also happens when I transpile the tests and run mocha on the command line. It also happens when I transpile and run the following file:
```
import { SuperModule } from "./super";

class Test extends SuperModule {
    constructor() {
        super();
    }
}

new Test();
```
So I think this is not an issue related to Test Explorer or Mocha. My guess is that it has something to do with the mixture of Javascript and Typescript or the mixture of CommonJS (`exports.SuperModule = SuperModule
`) and ESM (`import { SuperModule } from "test/index";
`) or the mixture of the untranspiled and tanspiled `class` construct (the Javascript file isn't transpiled, so it uses Node's built-in `class` construct, whereas the Typescript file is transpiled and the `class` construct is translated to ES5).

**Comment by peni4142** [comment]
what do you use for compiling?
That I can report that to them.

**Comment by hbenl** [comment]
I used Typescript 3.7.3 for compiling and Node 13.3.0 for running.
Here's my test case:

`base.js` :
```javascript
class BaseClass {
}
exports.BaseClass = BaseClass;
```

`derived.ts` :
```typescript
import { BaseClass } from "./base";
class DerivedClass extends BaseClass {
    constructor() {
        super();
    }
}
new DerivedClass();
```

compiling `derived.ts` to `derived.js` and running that in Node I get the following error:
TypeError: Class constructor BaseClass cannot be invoked without 'new'
