### ISSUE TITLE
any doco on what the "sqwerkle" icon indicates?

### ISSUE THREAD

**Issue by SimonCropp** [hbenl/vscode-test-explorer#110]
![image](https://user-images.githubusercontent.com/122666/73416290-8da0b200-4368-11ea-9c1c-49c162b4d54a.png)

i cant get these tests to run. there is no hover help and no errors anywhere i can see

**Comment by SimonCropp** [comment]
seems to mean pending https://github.com/hbenl/vscode-test-explorer/blob/master/icons/pending.svg

but i cant get them to run. clicking the play icon does nothing

**Comment by AlexHaxe** [comment]
I don't think your issue is with vscode-test-explorer, because it only visualises what information test-adapters provide. 
Your comments give no indication on what test-adapter you are trying to use. Chances are it's either a configuration issue or a bug in that test-adapter.

@hbenl have you considered adding a github issue template?

**Comment by SimonCropp** [comment]
closing since i answered my own question
