### ISSUE TITLE
hello-world-testsample

### ISSUE THREAD

**Issue by maziac** [hbenl/vscode-test-explorer#116]
I tried to use the [hello-world-testsample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample) from microsoft.
But it is not working.
I get:
```
Error: Cannot find module 'source-map-support/register'
Require stack:
- /Users/.../.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at execute (/Users/bob/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js:1710:13)
    at /Users/.../.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js:1671:9
    at Generator.next (<anonymous>)
    at fulfilled (/Users/.../.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js:81:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/.../.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js'
  ]
}
```

**Comment by hbenl** [comment]
I don't know why you get that error, but even without that it wouldn't work anyway because the Mocha Test Adapter currently can't be used for tests written using `vscode-test` (like this sample project).
I think it should be possible to run `vscode-test` tests using a custom ["launcher script"](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter#user-content-running-tests-remotely) (usually used for running tests remotely). I will try to create a sample soon showing how this can be done and will let you know.

**Comment by hbenl** [comment]
I tried this but currently it isn't possible because `vscode-test` tests can only run when VS Code isn't running (or in a VS Code debugging session, which is also not suitable for the Test Explorer).
I created an [issue](https://github.com/microsoft/vscode-test/issues/57) for this.

**Comment by hbenl** [comment]
It's now possible to run `vscode-test` tests with this extension. There's some documentation [here](https://github.com/hbenl/vscode-mocha-test-adapter#running-vs-code-extension-tests-using-vscode-test) and there's a sample [here](https://github.com/hbenl/vscode-extension-samples/tree/test-explorer-integration/helloworld-test-sample) (this is actually the helloworld-test-sample with the necessary configuration for Mocha Test Explorer).
