### ISSUE TITLE
Jest 404

### ISSUE THREAD

**Issue by phoenix741** [hbenl/vscode-test-explorer#119]
Hi,

The plugin vscode-jest-test-adapter doesn't not exist anymore : 

 * https://marketplace.visualstudio.com/items?itemName=rtbenfield.vscode-jest-test-adapter
 * https://github.com/rtbenfield/vscode-jest-test-adapter

Do you have an alternative ?

Can you update your dependencies ?

**Comment by Martinspire** [comment]
It seems that rtbenfield removed his github account or something because everything is removed there. I did see that https://github.com/hbenl/vscode-example-test-adapter might have taken over, but it is now marked as a template instead and I'm not sure who is now publishing it. In any case, no Jest adapter has been published to the extension site. So I'm not sure how to use it right now

**Comment by hbenl** [comment]
A new [Jest Test Explorer](https://marketplace.visualstudio.com/items?itemName=kavod-io.vscode-jest-test-adapter) extension (forked from the removed one) has been published to the marketplace.
