### ISSUE TITLE
[Feature] Debugging suites

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#138]
Hello.

For developing a new feature I need the following:

1. Ability to send test load started and finished (loading session) events during testing session.
2. Replacing a 'test' (leaf) with a suite (and it's children of course)
   - then sending events about those children under the running session.
3. Debug button on suite

I'm not sure but it seems like the 1st is already working. That support that idea that the 2nd might works too. Only 3rd requirement left. For that adding an `isDebuggable?:boolean` flag to `TestSuiteInfo` seems convenient.

What do you think?

**Comment by hbenl** [comment]
1. yes, this is already possible. Adapters can load and run tests whenever they want to, the load/run requests are only meant to relay the user's wishes. Ideally in this situation your adapter should send the events in this order: `TestLoadStartedEvent`, `TestLoadFinishedEvent`, `TestRunStartedEvent`, ... , `TestRunFinishedEvent`. In other words: the loading and running of the tests shouldn't overlap. That's not a strict requirement, but Test Controllers may get confused otherwise (this happened with Test Explorer itself in the past).
2. If you mean that the `TestLoadFinishedEvent` replaces a test with a suite: yes, that's already possible.
3. Debugging suites was already possible (through the suite's code lenses), only the button didn't show up in the Explorer because I thought there was no use case for this. Now that I know that there is, I've enabled those buttons (in version 2.18.1)

**Comment by matepek** [comment]
You mean adding debug button for all the suites too? Isn't it too much. In my case only some special suites (which are actually tests) could be debugged.

**Comment by matepek** [comment]
3. I know in case of mocha debug button makes sense for all the suites too but in my case it makes sense just in some cases. Now I have to throw an exception if the user tries to debug a "wrong" suite. It works, but.. a switch on the `TestSuiteInfo` would be nicer. ^^

**Comment by hbenl** [comment]
> You mean adding debug button for all the suites too? Isn't it too much. In my case only some special suites (which are actually tests) could be debugged.

Well, the adapters had to support debugging suites anyway (as it's always been accessible using the code lenses). The change only made the UI a bit more consistent.
But I do understand the desire to be able to tell which suites (and maybe also tests) are debuggable and which aren't. I'll add a `debuggable` flag to `TestInfo` and `TestSuiteInfo`.

> So for me that would be great if I could send events in the following order too: ...

Have you tried this? It should already be working, but I wouldn't be surprised if it isn't - in which case I would fix this, but I feel it would kinda prove my point that this kind of overlap has a good chance of triggering bugs in Test Controllers (although they _should_ be prepared for this, but it's easy to make mistakes there)...

**Comment by matepek** [comment]
> I'll add a debuggable flag to TestInfo and TestSuiteInfo.

Lovely, thanks.

> Well, the adapters had to support debugging suites anyway 

I reworked my extension and currently it is not guaranteed that tests from the same executable under the same suite. And 2  executables cannot be debugged in the same time. (Actually it can, but it doesn't make sense in my case)

> Have you tried this?

Yes, it's working.. and it is in production for a week. I was just afraid that I'm only lucky and I'm saying it would be nice if it would be supported 😊

**Comment by hbenl** [comment]
> I was just afraid that I'm only lucky and I'm saying it would be nice if it would be supported

Yeah, it's good that you mention this - even though I had designed Test Explorer to allow this in principle, I had never taken this seriously, thinking it probably wasn't used by anyone. So from now on I will keep this kind of scenario in mind.

**Comment by matepek** [comment]
Well then I must say you really thought this trough 👍

**Comment by hbenl** [comment]
In the latest version of Test Explorer's API you can add `debuggable: false` to `Test(Suite)Info` to remove the debug icon and code lens.
