### ISSUE TITLE
add jest adapter

### ISSUE THREAD

**Issue by capaj** [hbenl/vscode-test-explorer#14]
we use jest exclusively for our testing, so it would be awesome if you could add an adapter for it.

**Comment by thejuan** [comment]
Jest uses Jasmine. Is it possible to use the Jasmine adapter?

**Comment by nonameolsson** [comment]
This would be awesome. Any progress on this? Any way to help?

**Comment by hbenl** [comment]
I am not using Jest myself, so I don't feel I'm qualified to be the main developer and maintainer of a Jest adapter, but I would contribute to the development of such an adapter.

The main challenge when writing a Test Adapter is usually discovering the tests and finding their source locations (filename and line number).
* Discovering the tests: In the Jasmine adapter I do this with a [Reporter](https://github.com/hbenl/vscode-jasmine-test-adapter/blob/master/src/worker/loadTestsReporter.ts). I tell Jasmine to run the tests matching the regular expression `$^` with this Reporter - this expression matches nothing, so none of the tests will actually be run, but Jasmine will tell the Reporter about their existence anyway. Jest has a different Reporter API, so the Jasmine Reporter can't be reused here, but it shouldn't be hard to write a corresponding Jest Reporter.
* Finding the tests' and suites' source locations: I know 3 ways to do this:
  1. simply searching the test files for lines containing the title of each test/suite. This is the easiest to implement, but has some problems:
      * if the title of a test or suite is dynamically created, the location of that test/suite won't be found
      * if the title of a test or suite appears somewhere else in the sources, the wrong location may be found
  2. parsing the sources of the tests and searching for `it`/`describe` calls in the syntax tree.
     This eliminates the problem with detecting the wrong locations for some tests/suites, but is still not able to detect tests with dynamically created titles.
  3. monkeypatching the `it`/`describe` functions so that they can report their locations. This is the most reliable method but may also be the trickiest to implement. Have a look at [`patchJasmine.ts`](https://github.com/hbenl/vscode-jasmine-test-adapter/blob/master/src/worker/patchJasmine.ts) in the Jasmine adapter - this monkeypatch collects the locations in a `Map` and the Reporter then copies the location information from this `Map` to the `TestInfo`/`TestSuiteInfo` objects.

  I would advise starting with the first option and then, once the adapter is working, trying to implement the third option. Note that even if the adapter doesn't find the tests' locations, it will still work, but you don't get the Code Lenses and Decorations next to the tests anymore.

If someone implements this test discovery, I will gladly help to integrate it into a Jest adapter.

**Comment by rtbenfield** [comment]
I have been experimenting with this on and off for a while now and got a working version up this weekend. Today I cleaned it up from an experiment to a crude implementation and started pushing changes to [rtbenfield/vscode-jest-test-adapter](https://github.com/rtbenfield/vscode-jest-test-adapter). I haven't pushed this to the VS Code Marketplace yet because there are still a few things to clean up, such as better process management, cancel support, and compatibility across various configurations. I plan to open some issues, possibly PRs, with the [jest-editor-support](https://github.com/jest-community/jest-editor-support) project to make things a bit less clumsy. I'd love to get feedback on the progress so far.

**Comment by rtbenfield** [comment]
@thejuan I actually published a preview version last week to the Marketplace [here](https://marketplace.visualstudio.com/items?itemName=rtbenfield.vscode-jest-test-adapter). It is still in early stages and I know there is a lot of work to do in detecting various environments and configurations, but it should work when Jest is installed and configured in the root of the open workspace folder. If you could try the version from the Marketplace and, if it doesn't work for you, report an issue to [rtbenfield/vscode-jest-test-adapter](https://github.com/rtbenfield/vscode-jest-test-adapter) with your environment setup (ex. are you using a project template) that would be awesome.

**Comment by thejuan** [comment]
Awesome! Its now finding my .js tests, I've raised an issue for .ts/.tsx tests.
The js project requires custom running of jest (CreateReactApp 2.1 ) so can't run the tests yet.
