### ISSUE TITLE
Adding suites and tests discovered at runtime

### ISSUE THREAD

**Issue by rossknudsen** [hbenl/vscode-test-explorer#142]
I'm working on trying to get my test adapter to add suites and tests when they are discovered at runtime.  The `TestSuiteEvent` and `TestEvent` indicate that if I supply a `TestSuiteInfo`/`TestInfo` along with those events, then those suites/tests will be added.

However, looking at the source, it seems that they are only added when the events are in the 'running' status, not 'completed'.  Unfortunately, I only discover the tests after execution, so I want to emit them at completion.

**Comment by AlexHaxe** [comment]
In Haxe test adapter we also do discovery at runtime. In fact our test adapter watches for a specific file to learn about tests and results. Testruns usually write that file at the end of a run. Once we notice a change we parse results and pass them on to test explorer.

So it's possible to discover tests during runtime or even after.

**Comment by rossknudsen** [comment]
I've done some experimenting adding in code to emit dummy suites and tests at runtime for both the running and completed statuses.  The dummy tests and suites appear for the running events, but not the completed events.  

Looking at the source, there appears to be a problem with the handling of new suites in the completed state (see [here](https://github.com/hbenl/vscode-test-explorer/blob/master/src/tree/testCollection.ts#L233-L271)).  Notice that in the completed conditional, if `suiteNode` is undefined, then it is not added to the set of suites, but in the running conditional it is added (line 241 onwards).

**Comment by rossknudsen** [comment]
Actually, I may have understood why this behaves the way it does.  I see that the running and completion of suites updates `this.runningSuite`, navigating through the suites/tests.  I think I need to change the way I implemented my code to handle the tree traversal correctly.

**Comment by AlexHaxe** [comment]
It's been a while since I implemented it, but as far as I can recollect (and see from sources), we emit a `TestRunStartedEvent` and then we wait until test run completes. Our test results are file based, so a file watcher will trigger a reload of our results file which will then emit a `TestLoadStartedEvent` and almost immediately after `TestLoadFinishedEvent` with all suite and child info we discovered. 
And then we fire `TestEvent`s for every test found in our file (I don't think we emit `TestSuiteEvent`, but that should work as well).
After that we complete our run with a `TestRunFinishedEvent` which will return tree icons from their blue state to green or red.

The same thing happens when you restart VSCode, because we still have results from the last test run. 

Our approach means that new tests will only appear in explorer once you run all or their class or package, but we are able to support six different test frameworks and lots of different target platforms (e.g. Javascript, Java, C++, PHP, etc.)

**Comment by hbenl** [comment]
>  I see that the running and completion of suites updates this.runningSuite, navigating through the suites/tests.

Exactly, this feature is intended for adding suites and tests _while_ you're navigating through the suites/tests. Useful when the test run may take a long time but you want the newly discovered suites/tests to show up immediately.
 
> Unfortunately, I only discover the tests after execution, so I want to emit them at completion.

You could send a `TestLoadStartedEvent`/`TestLoadFinishedEvent` combo with the complete test tree during the test run (before you send the `TestEvent`s for the newly discovered tests - otherwise Test Explorer will ignore the `TestEvent`s for tests it doesn't know about yet).

**Comment by rossknudsen** [comment]
Awesome.  I managed to figure it out - thanks for humoring me 😅.  I now get runtime discovered tests in the correct location by emitting the discovered tests when emitting the 'running' events.  This has the side effect of all the tests having the indeterminate state while the tests are executing:
![image](https://user-images.githubusercontent.com/2489915/83369428-748c3880-a410-11ea-80f9-0203dbe642e0.png)
But I'm going to try emitting the running events twice.  I think the host extension can cope with that, but if it doesn't then I'll stick with the current behavior.  But I'll close this issue now.
