### ISSUE TITLE
Class as additional tree item in the test explorer

### ISSUE THREAD

**Issue by Kakunas** [hbenl/vscode-test-explorer#165]
![Unbenannt](https://user-images.githubusercontent.com/73190922/96685051-dd9f2900-137c-11eb-9191-b2b7706467a1.JPG)
As seen in the picture. The VisualStudio have an additional tree item for a better overview.
Maybe that is also possible at VisualStudio Code.
In that case: Main.Safety is the Namespace the next Safety is the class name. The last element is the testcase.

**Comment by AlexHaxe** [comment]
I think that is something that is up to individual test-adapters, because test explorer already supports it (if adapters care to use it). e.g I added support for it in [Haxe's test-adapter extension](https://github.com/vshaxe/haxe-test-adapter).

also: hierarchical tree items might mean something different depending on which test frameworks you're using. 
e.g. BDD based test frameworks use `describe` calls to define testsuites. and they can sit in just one file or distributed over multiple files. they can even use nested `describe` calls. they don't use packages or module names of files containing test cases, because they are not relevant to BDD. 
so it has to be up to each test-adapter to add support for hierarchical tree items, because only they know what a correct representation looks like.

**Comment by Kakunas** [comment]
Ok. Then the problem might be at the NXunit Test Explorer, which is based on this test explorer.
