### ISSUE TITLE
Start only project language related extensions

### ISSUE THREAD

**Issue by gquittet** [hbenl/vscode-test-explorer#168]
I've installed the Python Test Explorer UI extension and Jest Test Explorer.

The problem is Test Explorer launch the Python Test Explorer extension that launch the Python extension in my Typescript project.

Is it possible to check the language of the project / running extensions to launch only the language specific Test Explorer extension ?

**Comment by AlexHaxe** [comment]
test explorer doesn't control when test adapter extensions start and it doesn't launch them by itself, because test explorer doesn't know which extensions are available and active for your workspace.

vscode launches your test adapter extensions according to `activationEvents` defined in each extension's `package.json` configuration: see [Python's activationEvents](https://github.com/kondratyev-nv/vscode-python-test-adapter/blob/15d82ef74d17b167eef3384ce8104310dacb5f8f/package.json#L96-L107) and [Jest's activationEvents](https://github.com/kavod-io/vscode-jest-test-adapter/blob/abe458db6016848372807813699a1cb6afe3f839/package.json#L89-L91)

as you can see Python test adapter tries to limit activation to events around test explorer and Python but includes an `onStartupFinished` event which fires regardless of language or test framework. Jest's activation is a bit more generous, it uses `*` which is similar to `onStartupFinished`, but in addition might slow down VSCode startup.

however even if you can get Python test adapter to remove `onStartupFinished` and Jest test adapter to use a more constraint `activationEvents` definition you will still end up launching both extensions as soon as you open test explorer view (because it makes sense that all test adapters listen and active on that event). 

so to get what you want you will need to disable extensions per workspace so they remain dormant when they aren't needed.

**Comment by gquittet** [comment]
This Workaround will do the trick.

Thank you!
