### ISSUE TITLE
Request: Karma Test Adapter

### ISSUE THREAD

**Issue by persn** [hbenl/vscode-test-explorer#19]
It would be nice to support Karma Test Runner https://karma-runner.github.io/latest/index.html

**Comment by perrosen** [comment]
I second that. Doesn't seem to be much love on the marketplace for Karma either so would be really great!

**Comment by AlbertoBonfiglio** [comment]
I wouldn't mind to collaborate to put one together

**Comment by persn** [comment]
> I wouldn't mind to collaborate to put one together

I set up a repo [here](https://github.com/persn/vscode-karma-test-controller) using the template for test extensions. It was meant for experimentation but maybe we could make something of this. I'll try and populate the Issues tab with tasks in the weekend.

**Comment by hbenl** [comment]
I am not using Karma myself, so I don't feel I'm qualified to be the main developer and maintainer of a Karma adapter, but I would contribute to the development of such an adapter.

The main challenge when writing a Test Adapter is usually discovering the tests and finding their source locations (filename and line number).
* Discovering the tests: In the Jasmine adapter I do this with a [Reporter](https://github.com/hbenl/vscode-jasmine-test-adapter/blob/master/src/worker/loadTestsReporter.ts). I tell Jasmine to run the tests matching the regular expression `$^` with this Reporter - this expression matches nothing, so none of the tests will actually be run, but Jasmine will tell the Reporter about their existence anyway. I don't know Karma's Reporter API, but it shouldn't be hard to write a corresponding Karma Reporter.
* Finding the tests' and suites' source locations: I know 3 ways to do this:
  1. simply searching the test files for lines containing the title of each test/suite. This is the easiest to implement, but has some problems:
      * if the title of a test or suite is dynamically created, the location of that test/suite won't be found
      * if the title of a test or suite appears somewhere else in the sources, the wrong location may be found
  2. parsing the sources of the tests and searching for `it`/`describe` calls in the syntax tree.
     This eliminates the problem with detecting the wrong locations for some tests/suites, but is still not able to detect tests with dynamically created titles.
  3. monkeypatching the `it`/`describe` functions so that they can report their locations. This is the most reliable method but may also be the trickiest to implement. Have a look at [`patchJasmine.ts`](https://github.com/hbenl/vscode-jasmine-test-adapter/blob/master/src/worker/patchJasmine.ts) in the Jasmine adapter - this monkeypatch collects the locations in a `Map` and the Reporter then copies the location information from this `Map` to the `TestInfo`/`TestSuiteInfo` objects.

  I would advise starting with the first option and then, once the adapter is working, trying to implement the third option. Note that even if the adapter doesn't find the tests' locations, it will still work, but you don't get the Code Lenses and Decorations next to the tests anymore.

If someone implements this test discovery, I will gladly help to integrate it into a Karma adapter.

@persn you need to fork the [Test Adapter example](https://github.com/hbenl/vscode-example-test-adapter), not the Test Controller example. The Adapters contain the integration with the test frameworks, the Controllers contain the UI for controlling the adapters.

**Comment by persn** [comment]
> you need to fork the Test Adapter example, not the Test Controller example. The Adapters contain the integration with the test frameworks, the Controllers contain the UI for controlling the adapters.

Oops! Thanks for telling me, I'll take care of it soon

**Comment by persn** [comment]
Hope I didn't screw up twice

https://github.com/persn/vscode-karma-test-adapter

**Comment by jonasbg** [comment]
> Hope I didn't screw up twice
> 
> https://github.com/persn/vscode-karma-test-adapter

Does it work?
Would be great to have this for Karma (Angular 2+) tests....

**Comment by persn** [comment]
> Does it work?

Work hasn't begun yet. It's just a sandbox for anyone who wants to start experimenting at this point

**Comment by AlbertoBonfiglio** [comment]
Cool. My classes are over this week so I'll have time to play next week

**Comment by RichiCoder1** [comment]
@persn I may make some contributions too. Looks like Karma has an official nodejs lib we can potentially plug into https://karma-runner.github.io/3.0/dev/public-api.html

**Comment by persn** [comment]
I won't be able to find the time to work on this anytime soon so anyone is welcome to just take over entirely

**Comment by hbenl** [comment]
@RichiCoder1 There is a Karma adapter being actively developed, have a look at hbenl/vscode-example-test-adapter#1
