### ISSUE TITLE
Question: Considered taking a dependency on the vstest platform?

### ISSUE THREAD

**Issue by kendrahavens** [hbenl/vscode-test-explorer#21]
Hi, just a question here.

I was wondering if you had considered using the [vstest platform](https://github.com/Microsoft/vstest) as the underlying test runner for this extension? It's cross-platform, extensively used, open source, and community test adapter authors are familiar with it because of the Visual Studio extensions they've written. It's definitely not fine-tuned to the VSCode scenario, but I feel like a lot of functionality could be reused. I'd also love to hear what may have made you decide against it if you had considered it.

Thank you for your time!

**Comment by hbenl** [comment]
No, mostly because it is based on .Net and VS Code isn't. I've never really looked into this but I think that writing a VS Code extension that uses .Net could be challenging.
Of course it would be nice if Test Adapters written for the vstest platform could run in VS Code. This could be done in a separate extension that puts a wrapper around a vstest adapter that translates between the APIs and then registers that wrapper with this Test Explorer.

**Comment by kendrahavens** [comment]
An extension wrapping the test platform and adapters is definitely a good option too. Thank you for the extra info!

**Comment by yozlet** [comment]
Two VSCode extensions worth looking at for this:

* [VSTest Tools Framework](Frahttps://marketplace.visualstudio.com/items?itemName=gfrancischini.vscode-vstest-framework) - hasn't been updated in a year, but the code looks fairly simple and may be easy to integrate into Test Explorer. However, it's described as a "Work In Progress" so may have some missing functionality or major bugs.
* [.NET Test Explorer][https://github.com/formulahendry/vscode-dotnet-test-explorer] - actively maintained, much bigger, but also implements much of _this_ Test Explorer's functionality.
