### ISSUE TITLE
Support for VsCode v1.54.1+

### ISSUE THREAD

**Issue by Earthii** [hbenl/vscode-test-explorer#210]
Seems like It currently doesn't support version 1.54.1. Are there any plans to fix this?

For anyone wanting a temporary solution, you can downgrade the extension to version "2.20.1"

**Comment by cnx-tcsikos** [comment]
It works for me with:
VsCode 1.56.2
Test Explorer UI v2.20.2
Test Adapter Converter v0.0.9

**Comment by The-Compiler** [comment]
No issues here with VS Code 1.57.0 (and 1.56.2 before that) and Test Explorer UI 2.20.2 either FWIW.

**Comment by hbenl** [comment]
Sorry, I made a mistake when I added an extension dependency to the [converter extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.test-adapter-converter) which needs VSCode 1.55.0 and I didn't update the minimum VSCode version of this extension. As a result, older VSCode versions upgraded to the latest version of this extension and then failed to load it because they couldn't install the extension dependency.
This should be fixed with versions 2.20.3 and 2.20.4 (2.20.3 removes the extension dependency and older VSCode version should automatically upgrade to (and work with) that version, 2.20.4 is essentially the same as 2.20.2, but now the minimum VSCode version is 1.55.0, so older VSCode versions won't upgrade to that version).
