### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kemicky** [hbenl/vscode-test-explorer#219]
Extension error

**Comment by AlexHaxe** [comment]
can you give a more detailed description of your issue? (and with more detailed I mean a lot more, like a lot lot more)

a step by step walkthrough on how to get from zero to where your problem lies would be a start. 
also what actual test adapter are you using? (because maybe the issues lies over there?)

**Comment by kemicky** [comment]
It is complaining  about some virus thst is affecting a repository..and I
dnt know how to solve that problem. Can you please check. Thank you

**Comment by hbenl** [comment]
Sorry, your issue must be somewhere else. There is no virus in this repository.
