### ISSUE TITLE
Request: xunit xml support?

### ISSUE THREAD

**Issue by jamescasbon** [hbenl/vscode-test-explorer#22]
Xunit xml offers a normalised way of reporting test results: https://xunit.github.io/docs/format-xml-v2 

It seems to have fairly wide support in test runners.   If test explorer supported this, it could be easier for adapter authors to report rich results  eg ( https://github.com/kondratyev-nv/vscode-python-test-adapter/issues/5 )

**Comment by hbenl** [comment]
If someone implements this, I could add it to the [util package](https://github.com/hbenl/vscode-test-adapter-util) so that other adapter authors can reuse it.
However, I see several problems with this:
* I think the junitxml format  mentioned in the linked issue is not the same as the xunit xml format
* the junitxml format does not contain messages from `stdout`, so it wouldn't solve the linked issue
* I think the xml is only created at the end of the test run - if you have tests that take some time to run, it's nicer to see the results appear as the test run progresses (this is usually implemented using a test reporter that sends messages to the test adapter)
