### ISSUE TITLE
Error Decoration Hover not working with new VS Code version

### ISSUE THREAD

**Issue by EngineerChris** [hbenl/vscode-test-explorer#232]
Test Explorer version: v2.21.1
VS Code version: 1.64.0
OS: Windows 10 1909

As stated in the title, with the update to VS Code 1.64.0, Error Decoration Hover is not working correctly. With the setting enabled, upon hovering over an error, only a small black box is show (see image below):
![image](https://user-images.githubusercontent.com/57582158/153053674-a4b63b96-f0e6-41cd-a210-44ac1c9a5ac4.png)

**Comment by JDaance** [comment]
I have this as well with my plugin, I actually spent days migrating to the "native testing" feature because of this. But the native version is buggy and laggy, after trying to use it and filing bug reports for 1.5 months I really don't like it. It needs some kind of rearchitecturing to be as good as this plugin.

This bug happened for me with the january update (released beginning of february). Almost considering forking this plugin to get back to my old testing flow.

**Comment by JDaance** [comment]
I just set up a dev environment to try to debug `vscode-test-explorer` extension and now the hover is working already. Not sure if this is due to vscode being an even newer version, or something else. It might be a vscode bug that has been fixed since. I will start using it again and see if its stable.

**Comment by JDaance** [comment]
Its working perfectly now for me, so issue can probably be closed
