### ISSUE TITLE
Expose & use TreeItem description and/or resourceUri through API for file differentiation

### ISSUE THREAD

**Issue by yozlet** [hbenl/vscode-test-explorer#25]
I'm working on a project which has multiple folders below the project root, and each folder has its own `tests.py`. So my Test Explorer looks like this:
![image](https://user-images.githubusercontent.com/173848/50177182-2b950280-02b6-11e9-845c-cd5246e6ab02.png)
... which is not hugely helpful when trying to find the right one. (I'm using the [Python Test Adapter](https://github.com/kondratyev-nv/vscode-python-test-adapter/), but this problem could apply to all of them.)

When dealing with multiple identically-named files, VSCode's practice is to differentiate on path by adding a smaller path description to tab headers:
![image](https://user-images.githubusercontent.com/173848/50177413-cee61780-02b6-11e9-83e1-be365be3c287.png)

Note that VSCode includes logic to work out the best text for these descriptions, based on where the paths differentiate.

These smaller, lighter/darker labels (a.k.a. _Descriptions_) are [now available in extension tree views](https://code.visualstudio.com/updates/v1_30#_custom-views). You can provide the string for the description directly, or simply tell VSCode to work it out (using its path differentiation logic) from the TreeItem's `resourceUri`, which might be much easier.

**Comment by matepek** [comment]
I got a feature request: [this](https://github.com/matepek/vscode-catch2-test-adapter/issues/79)
This is **description** related too.

I copy my proposal from a closed pull request:

Adding a `description?: string` to *TestSuiteInfo, TestInfo, TestSuiteEvent and TestEvent*.
Initially *TreeItem#description* is filled with *TestSuiteInfo*'s and *TestInfo*'s description if provided and could be overwritten by the event's `description` property if provided.

(Maybe the `tooltip` property could be updated through events.)

**Comment by hbenl** [comment]
@matepek I just published a new version of Test Explorer and its API with the ability for adapters to set the description of tests and suites when loading and running. The tooltips can now also be changed when running.

@yozlet Since adapters can now set the descriptions, you should ask the developers of the Python adapter to add this feature. I also experimented with the possibility to let VS Code derive the descriptions from the `resourceUri` but I found the result not very convincing, that's why I decided it's probably not worth adding this special case to the Test Explorer.
