### ISSUE TITLE
Run test explorer in docker-compose

### ISSUE THREAD

**Issue by DamickDoni** [hbenl/vscode-test-explorer#53]
As the title says. Is it possible to run the test explorer in docker-compose? (I must run grunt inside of docker)

**Comment by hbenl** [comment]
Well, the Test Explorer can't be run in a container because it needs to run in VS Code's extension host process. But a Test Adapter may implement this feature to run the tests in a container. In fact, I've been experimenting with this a while back with my Mocha Adapter and I hope I will find the time soon to finish this feature.
Which testing framework do you use?

**Comment by DamickDoni** [comment]
I use Mocha

**Comment by hbenl** [comment]
This is now supported by [Mocha Test Explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter#user-content-running-tests-remotely): you'll have to write a launcher script that runs the tests in docker - there is an [example project](https://github.com/hbenl/vscode-mocha-docker-example) for running tests in a docker container that contains a well-documented launcher script (it doesn't use docker-compose, but it shouldn't be too hard to adapt it to your needs) and [a project](https://github.com/hbenl/vscode-test-adapter-remoting-util) containing further documentation and utility functions to use in the launcher script.
