### ISSUE TITLE
Suite description and tooltip cant be updated with TestSuiteEvent just at first time 

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#54]
Easy setup:
1 suite with 2 tests.
I run the suite after and after, updating the suite and the test descriptions and events too.
Test infos update but suite infos don't.

**Comment by matepek** [comment]
I guess somwhere nearby 
https://github.com/hbenl/vscode-test-explorer/blob/8f1f7a11c603cf8902a3967dec891decbc327251/src/tree/testSuiteNode.ts#L72-L74

**Comment by hbenl** [comment]
Well spotted! Initially I couldn't reproduce this but your last comment made me understand what's going on.
I have published a temporary workaround (which may hurt performance with large trees, so I'll have to do a proper fix soon).

**Comment by matepek** [comment]
There is this short "reloading" effect while tests are running. See attached video.
[Screen Recording 2019-04-01 at 22.11.11.zip](https://github.com/hbenl/vscode-test-explorer/files/3031174/Screen.Recording.2019-04-01.at.22.11.11.zip)
I guess this is related to your quick-fix.

**Comment by hbenl** [comment]
I released the proper fix yesterday and now the reloading effect is less pronounced, but it's still there. So I tried with an older release (before the quick fix) and there I could also see the reloading effect. But without the quick fix (and now with the proper fix) it's barely noticeable for me, so maybe that's why we didn't notice it in the past. And/Or maybe it is a relatively new UI change in VS Code.
It seems to happen every time a top-level node is changed, so updating suite descriptions often could exacerbate this.
