### ISSUE TITLE
test results greyed out when retire getter missing from adapter

### ISSUE THREAD

**Issue by AlexHaxe** [hbenl/vscode-test-explorer#59]
Hi,

when using Haxe Test Explorer extension I noticed that my test results always showed up with correct icons but they remained greyed out (or fainted?) instead of showing in solid colours like they used to.

I fixed it in Haxe Test Explorer bei adding a `retire` getter, even though it's marked as optional. 
It seems test explorer's handling of old API adapters is broken.

**Comment by hbenl** [comment]
This was a deliberate change in version 2.9.0: the greyed out icons indicate that the test states may be outdated, so this happens every time the tests are reloaded (because that usually means the tests have changed).
In the past, this was off by default, so after a reload an autorun was triggered (if the user enabled autorun) but the state icons were not greyed out. The inconsistent handling of greying out the icons and the autorun feature (which is closely related: tests should be run when their states may be outdated) caused some confusion, so I decided to handle these 2 features more consistently.
At the same time I introduced the `retire` event which allows the adapter to tell Test Explorer exactly which tests may be outdated. When you implement the `retire` event the Test Explorer doesn't automatically assume all tests are outdated after reloading anymore. Instead it waits for your adapter to send a `retire` event to tell it which tests are outdated. So if one of many test files changes, you can tell the Test Explorer that only the tests in that file may be outdated and consequently only those tests will have their state icons greyed out and only those tests will be run if the user enabled autorun.
Sorry about the confusion, but I think the new behavior is more consistent.

**Comment by AlexHaxe** [comment]
I understand why `retire` was introduced and what it's meant to do, but at least for Haxe Test Explorer that was sort of a (minor) breaking change. Because if you don't update your API and include a `retire` getter, your results will change their looks. 

I am not sure, if Haxe's adapter is special since it operates on a file based communication between adapter and actual test runners (we support 6 different test frameworks and they can use almost any target platform supported by Haxe to run on from nodejs to C++ or C# or Java or PHP, etc.). I don't have a test project for one of the other test adapter implementations to see if they expose the same behaviour.

From looking at the sources and CHANGELOG it didn't seem like it was a breaking change, maybe it should be marked as such.

**Comment by hbenl** [comment]
> I am not sure, if Haxe's adapter is special [...]

No, this affects all adapters.

> From looking at the sources and CHANGELOG it didn't seem like it was a breaking change, maybe it should be marked as such.

Yeah, I should have made that clear in the Changelog. My apologies, I have added a clarification to the Changelog now and will do so again if I make another breaking change (which I usually avoid, knowing that it can be irritating for adapter authors).
