### ISSUE TITLE
[Question] Is there a chance that UI for the TestExplorer is modificable by the adapter?

### ISSUE THREAD

**Issue by Raagh** [hbenl/vscode-test-explorer#64]
Hey man how you been? so I am facing this issue. 

In Angular one project can have multiple apps all with independent suites of tests, and they are run separately. It would be awesome to have like a select component in the UI so the user can pick the project they want to test, when that happens loadTests is triggered with the name of the project.

How does the UI works? can I make that change myself?

**Comment by hbenl** [comment]
I _think_ that you could contribute a button or menu entry to the UI (AFAIK VS Code doesn't restrict the menu contributions to be from the same extension that contributed the view, so _your_ extension can add buttons to the `test-explorer` view just like the Test Explorer itself can). That button could open a `QuickPick` showing all apps in the current project, and when the user picks one of those apps, the adapter could simply load the tests and send the corresponding `TestLoadEvent`s to the explorer.

But you could also show the apps in the test tree: the children of the root node could be suites representing the apps and each of these app nodes would have the tests for that app as children. Maybe that UI would even be more straightforward.

**Comment by Raagh** [comment]
Yes so, that was my original idea. The problem with that is that each app has its own karma.conf, this implies that for doing that I would need to launch karma one time with a different config just to load the tests from each app at the same time. That would also means that I have to keep open multiple karma process to track tests from all apps. I think it's complicating myself too much, or do you see another way of doing it?

**Comment by hbenl** [comment]
No, I don't see a simpler way of doing it - there's going to be some extra complexity one way or the other...
To contribute a button, you do exactly what Test Explorer itself does:
* add a [command](https://github.com/hbenl/vscode-test-explorer/blob/179fbc7cdbcc8b353557b0c016427e758d01178b/package.json#L174) to `contributes.commands` in `package.json`
* [reference](https://github.com/hbenl/vscode-test-explorer/blob/179fbc7cdbcc8b353557b0c016427e758d01178b/package.json#L296) that command to `contributes.menus.view/title` in `package.json` with a `when` condition containing `view == test-explorer` (add it to the `navigation` group and give it an icon if you want it to appear directly in the title bar, otherwise it will appear in the title bar menu)
* [register](https://github.com/hbenl/vscode-test-explorer/blob/179fbc7cdbcc8b353557b0c016427e758d01178b/src/main.ts#L38) that command in your `activate()` function
* the button should only be shown when the user has opened an angular project - you can achieve this by adding a property to the `when` condition of your `contributes.menus.view/title` contribution and setting that property with the `setContext` command (example: see [here](https://github.com/hbenl/vscode-test-explorer/blob/179fbc7cdbcc8b353557b0c016427e758d01178b/package.json#L298) and [here](https://github.com/hbenl/vscode-test-explorer/blob/179fbc7cdbcc8b353557b0c016427e758d01178b/src/testExplorer.ts#L278))
* the implementation of your command will need access to your adapter(s) (multiple if the user has a multi-folder workspace) - you can use [TestAdapterRegistrar#getAdapter()](https://github.com/hbenl/vscode-test-adapter-util/blob/7afebf2f4457121c98dc1db82adeeeb10af37d0c/src/registrar.ts#L43) in the latest version of the `vscode-test-adapter-util` package for that.

As you can see, extending the Test Explorer UI also incurs some complexity...

**Comment by Raagh** [comment]
I went with adding a button that will lunch a quickpick with the names of all the projects and when the user selects one it will trigger load for that project. when I finish the pull request do you mind reviewing it? at least the part of the command and button in case I am missing something.
