### ISSUE TITLE
File path should never be file://?

### ISSUE THREAD

**Issue by connorshea** [hbenl/vscode-test-explorer#77]
The `file` attribute for `TestInfo` and `TestSuiteInfo` objects says this:

>The file containing this test (if known). This can either be an absolute path (if it is a local file) or a URI. Note that this should never contain a `file://` URI.

But `vscode.workspace.workspaceFolders[0].uri` returns a URI like `file:///Users/connorshea/Programming/vglist/spec/requests/users/sessions_spec.rb`, and it works fine. What's the reasoning for the warning?

**Comment by connorshea** [comment]
and of course immediately afterwards I discover that `uri` has an `fsPath` attribute 🤦‍♂ 

I'm still interested in the answer anyway :)

**Comment by hbenl** [comment]
> What's the reasoning for the warning?

The warning is more of a precaution: initially, I designed Test Explorer for local files only - my thinking was that the test framework usually wouldn't be able to access remote files anyway, so I went with paths instead of URIs. When I added [support for VS Live Share](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer-liveshare), I had to add support for URIs, but had to keep support for paths as well (to stay compatible with existing adapters). So now there were 2 ways to specify local paths and I felt it was prudent to advise people to stick to the one that was already well-tested.
