### ISSUE TITLE
Selecting a test with no output hides the entire bottom panel

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-test-explorer#84]
![](https://drive.google.com/uc?id=1toboHmz0hYPnbGxveFgkfuT_Stb_60NH)
If the ``Output`` tab in the Bottom Panel is currently open and a test with no output is selected - the entire panel will be hidden. I have to manually restore it or select a test with an output. Quite annoying iyam. Why not just show empty ``Output``?

**Comment by Spown** [comment]
Also notice how after I first switch to ``Terminal`` it automatically switches to ``Output`` if I select a test but then, after the Panel autocloses and is restored the same action doesn't switch to ``Output`` and keeps ``Terminal`` active and the entire Panel open.

**Comment by hbenl** [comment]
> Why not just show empty Output?

Because it hides part of the source code with an empty panel - personally I prefer the panel to disappear when it doesn't have any information to show. I could make this configurable though.

> the same action doesn't switch to Output and keeps Terminal active and the entire Panel open.

That is VS Code's decision - I just call `OutputChannel#hide()`. But in my opinion it makes sense: if an extension asks an OutputChannel to be hidden that isn't currently shown anyway, then there is nothing to do. After all, the extension only asked for that single OutputChannel to be hidden, not the entire panel.

Perhaps it would be nicer if calling `OutputChannel#hide()` while the OutputChannel is shown would restore the bottom panel's state to what it was before the OutputChannel appeared, but I can't influence that (VS Code doesn't give much information about the current state of the bottom panel and very little control over it).

**Comment by Spown** [comment]
> I could make this configurable though.

That would be nice. I need to see test's Output panel only occasionally. But I always need Debug and Terminal. So in my case a feature that I rarely use disables features that I need often and forces me to do additional steps to restore them.

Thank you.

**Comment by hbenl** [comment]
You can now use `"testExplorer.hideEmptyLog": false` to stop the automatic hiding of the bottom panel.
