### ISSUE TITLE
[Question] How does the UI shows the codelenses on top of the test(run, debug, show in explorer)

### ISSUE THREAD

**Issue by Raagh** [hbenl/vscode-test-explorer#86]
Hi again, sorry for asking so many questions today. I have noticed that although I am providing with the file path(FILE property in TestSuiteIInfo - NO LINE) where the test is located the gutter decorations on top of each test appear very randomly. I have to do view source on the test and then run it to see the decoration for that test, the same if I want them on all tests.

Is there a way to make decorations for all tests appear automatically on top of the tests when you open that file or at least when you do view source on the file?

**Comment by AlexHaxe** [comment]
I think its called codelens not gutter (gutter is to the side of your code).

As far as I know Test Explorer will show codelenses as soon as your adapter reports test and position info (if you omit position then you will see your test in explorer UI but no `view source`, no codelens and no gutter pass/fail/error icon).

Since test explorer doesn't know anything about your actual tests or what your adapter considers a valid test, it has to rely on data emitted from any active test adapter to show anything.

**Comment by Raagh** [comment]
Hi thanks for clarifying. The view source feature functions correctly just with the File property on TestSuiteInfo. The codelenses on the other hand the only appear after I did ViewSource and then run the test.

I am not providing the Line property though.

**Comment by AlexHaxe** [comment]
Without a line number there is no way for test explorer to show a codelense or gutter icons. I mean where should they be shown? 

Test explorer knows nothing about your file structure or syntax (could be any conceivable language and if you look at test explorer's readme there are many different implementations of test adapters for a number of test frameworks and languages), all it knows is what info your test adapter provides. So if you give partial information, then test explorer will try to work with it (`line` is an optional field), but it cannot magically come up with the missing bits.

If you don't provide a line number, I assume `Show source` just jumps to the top of your file and not to the actual test function.

**Comment by Raagh** [comment]
I understand what you re saying but it doesn't make sense to what I am seeing. When I hit viewsource it goes directly to the line of the test(not the top of the file). And again then why the gutter and codelenses appear after doing view source and run if I am still not providing the line value?

At some point the UI is figuring out the line of the test so I am wondering why it doesn't do it from the beginning.

**Comment by AlexHaxe** [comment]
Is your test adapter the only one running? And does it jump to the correct lines if you click on different test cases inside the same file? If yes to both then I'm confused.

**Comment by Raagh** [comment]
Yes to both, believe me I am as confused as you are ahah.
Tomorrow I will debug it to see if I can't get any extra information. Maybe @hbenl has some extra insights too.

Thank you for taking the time to answer me.

**Comment by Raagh** [comment]
@AlexHaxe its because of this. When you do view source without the line it actually finds the line for you. When you do run it activates codelenses after run.

`			let line = node.info.line;
			if (line === undefined) {
				line = findLineContaining(node.info.label, document.getText());
				node.info.line = line;
			}`

I am gonna steal that to provide the lines I think. The test explorer UI could also run that for every returned TestSuiteInfo with (testSuiteInfo.file && !testSuiteInfo.line) on loadTests

**Comment by AlexHaxe** [comment]
ok, that explains why it finds lines for test cases. 
When working on Haxe's test adapter I never saw that happen, but that may be related to the way it reports results. During my tests I never had codelens or `Show source` when position data was wrong.

I think in most cases `findLineContaining` works, but if you have two test classes that happen to use the same method name, or if you have two identical Jasmine style tests (`it("should do somthing")`) you might end up at an incorrect position, because it will only find the first occurance. But that's partially the developer's fault...

**Comment by Raagh** [comment]
Yes also I kind of enforce the user to fix those cases. I use the description as part of the id so I show a warning on the test when 2 tests have the same name. 

Well mistery solved. Now I can provide the line from the beginning. Thanks for your help on this. I will close the issue
