### ISSUE TITLE
Tests are failing with merge mismatch

### ISSUE THREAD

**Issue by dkuschmierz** [hbenl/vscode-test-explorer#87]
Hi, 

I have your plugin installed together with the vscode-catch2-test-adapter from Mate Pek and my tests are listed failing and I get the following error for all tests:

profiling: <PATH TO TEST>/external/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.gcda:Merge mismatch for function 1

When I run my test in the console, are are working properly. What is the problem here?

**Comment by AlexHaxe** [comment]
Test explorer only visualizes what a test adapter feeds it. So I would guess your issue is more with catch2-test-adapter (but I don't know anything about catch2, so I might be wrong).

I can't find "Merge mismatch" or "mismatch" in test explorer or in catch2 test adapter repositories, which points to some external tool reporting that error, maybe it's a tool that is being used by catch2 test adapter to collect test data - but that's just wild guesses.

**Comment by dkuschmierz** [comment]
@matepek Is it possible that this comes from your extension? What i find weird is, that the global gcno/gcda data is parsed and not that from the corresponding test

**Comment by matepek** [comment]
Are you using my extension or the fork “... (with code coverage)”

**Comment by dkuschmierz** [comment]
I‘m using the extension from the extension Manager

**Comment by matepek** [comment]
There are 2 extensions with similar name. But just one of it is mine. (The other is fork)

**Comment by dkuschmierz** [comment]
I‘m using your Extension,  not the fork

**Comment by matepek** [comment]
@dkuschmierz would you create propert bug report for me at my repo?

**Comment by dkuschmierz** [comment]
@matepek Yes sure, here is the link
[https://github.com/matepek/vscode-catch2-test-adapter/issues/115](url)

**Comment by matepek** [comment]
You can close this.
